# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_pizza_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='model.Topping'),
        ),
    ]
